from .js_delays_page import JsDelays
from .main_page import MainPage
from .formfields_page import FormFields
from .popups_page import Popups
from .slider_page import SliderPage
from .calendars_page import CalendarsPage
from .modal_page import ModalPage
from .hover_page import HoverPage
from .window_operations_page import WindowOperationsPage
from .ads_page import AdsPage
from .click_events_page import ClickEventsPage
from .spinners_page import SpinnersPage